name-template: '$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
template: |
  ## Changes

  $CHANGES

  ## Contributors

  $CONTRIBUTORS

categories:
  - type: "pre-exclude"
    when:
      label: 'skip-changelog'
  - type: "version-resolver"
    semver-increment: "major"
    when:
      label: 'major'
  - type: "version-resolver"
    semver-increment: "minor"
    when:
      labels:
        - 'enhancement'
        - 'feature'
  - type: "version-resolver"
    semver-increment: "patch"
    when:
      labels:
        - 'bug'
        - 'dependencies'
        - 'documentation'
        - 'rust'
        - 'github-actions'
  - type: "version-resolver"
    semver-increment: "patch"

autolabeler:
  - label: 'documentation'
    files:
      - '*.md'
      - 'docs/**'
      - 'wiki/**'
  - label: 'github-actions'
    files:
      - '.github/workflows/**'
  - label: 'rust'
    files:
      - 'Cargo.toml'
      - 'Cargo.lock'
      - 'src/**'
