on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths-ignore:
      - "**.md"
      - "docs/**"
      - "pv_docs/**"
      - "site/**"
      - "wiki/**"
      - ".github/ISSUE_TEMPLATE/**"

name: CI Build Flatpak

jobs:
  flatpak:
    name: "Flatpak"
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-50
      options: --privileged
    strategy:
      fail-fast: false
      matrix:
        manifest: [dev.nicx.mimick.local.yml, dev.nicx.mimick.yml]
        variant:
          - arch: x86_64
            runner: ubuntu-latest
          - arch: aarch64
            runner: ubuntu-24.04-arm
        exclude:
          # Only test the non-local manifest on x86_64 to save CI time, 
          # as it just downloads the remote tag instead of local source
          - manifest: dev.nicx.mimick.yml
            variant: { arch: aarch64, runner: ubuntu-24.04-arm }
    runs-on: ${{ matrix.variant.runner }}
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        submodules: recursive

    - name: Check if non-local manifest changed
      id: check_manifest
      run: |
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
        if [ "${{ github.event_name }}" == "pull_request" ]; then
          git fetch origin "${{ github.event.pull_request.base.sha }}" --depth=1
          CHANGED=$(git diff --name-only "${{ github.event.pull_request.base.sha }}" HEAD)
        else
          CHANGED=$(git diff-tree --no-commit-id --name-only -r HEAD)
        fi
        
        echo "Files changed:"
        echo "$CHANGED"
        
        if echo "$CHANGED" | grep -q "^dev.nicx.mimick.yml$"; then
          echo "Manifest was modified."
          echo "any_changed=true" >> "$GITHUB_OUTPUT"
        else
          echo "Manifest was not modified."
          echo "any_changed=false" >> "$GITHUB_OUTPUT"
        fi

    - name: Build Flatpak
      if: matrix.manifest == 'dev.nicx.mimick.local.yml' || steps.check_manifest.outputs.any_changed == 'true'
      uses: flatpak/flatpak-github-actions/flatpak-builder@92ae9851ad316786193b1fd3f40c4b51eb5cb101 # v6.6
      with:
        bundle: mimick.flatpak
        manifest-path: ${{ matrix.manifest }}
        cache-key: flatpak-builder-${{ matrix.manifest }}-${{ matrix.variant.arch }}-${{ hashFiles(matrix.manifest, 'Cargo.lock', 'cargo-sources.json') }}
        arch: ${{ matrix.variant.arch }}
        verbose: true
